### ISSUE TITLE
[suggestion] change correctAnswer to be an index, instead of value

### ISSUE THREAD

**Issue by simeydotme** [CharmaineHYM/quiz#1]
I noticed that the [`correctAnswer` property in the quiz-db](https://github.com/CharmaineHYM/quiz-database/blob/master/db.json#L7) was copying the exact text (value) from the `choices[]`. My suggestion is to use the index of the answer in the `choices[]` array instead.

for example;

```json
...
{
    "id": 3,
    "question": "Which HTML attribute is used to define inline styles?",
    "choices":["Style", "Font", "Styles", "Class"],
    "answer": 0
},
{
    "id": 4,
    "question": "The Property in CSS used to control element's font size is?",
    "choices":["text-style", "font-style", "text-size", "font-size"],
    "answer": 3
}
...
```

It would be a bit easier to maintain, and simpler to increase the # of questions... additionally it would be less prone to typos and could be translated easier if required. But it would require a bit of refactoring of the `Questions.vue` and `Score.vue`

:)

**Comment by CharmaineHYM** [comment]
thx Simon~ i changed to check answer with array index instead of string~
